CREATE DATABASE simplemooc

USE simplemooc
BEGIN TRANSACTION
CREATE TABLE "jet_pinnedapplication" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(255) NOT NULL, "user" integer unsigned NOT NULL, "date_add" datetime NOT NULL)
CREATE TABLE "jet_bookmark" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "url" varchar(200) NOT NULL, "title" varchar(255) NOT NULL, "user" integer unsigned NOT NULL, "date_add" datetime NOT NULL)
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL)
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL)
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL)
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL, "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id"), "user_id" integer NOT NULL REFERENCES "accounts_user" ("id"), "action_time" datetime NOT NULL)
CREATE TABLE "dashboard_userdashboardmodule" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "module" varchar(255) NOT NULL, "app_label" varchar(255) NULL, "user" integer unsigned NOT NULL, "column" integer unsigned NOT NULL, "order" integer NOT NULL, "settings" text NOT NULL, "children" text NOT NULL, "collapsed" bool NOT NULL)
CREATE TABLE "courses_course" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "slug" varchar(50) NOT NULL, "description" text NOT NULL, "about" text NOT NULL, "start_date" date NULL, "image" varchar(100) NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)
CREATE TABLE "core_empresa" ("id_emp" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "cnpj" varchar(20) NOT NULL UNIQUE, "razao" varchar(100) NOT NULL, "fantasia" varchar(100) NULL, "endereco" varchar(55) NOT NULL, "cidade" varchar(55) NOT NULL, "uf" varchar(2) NOT NULL, "cep" integer NOT NULL, "ativo" bool NOT NULL, "data_cadastro" datetime NOT NULL)
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id"), "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL)
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id"), "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id"))
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(80) NOT NULL UNIQUE)
CREATE TABLE "accounts_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "accounts_user" ("id"), "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id"))
CREATE TABLE "accounts_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "accounts_user" ("id"), "group_id" integer NOT NULL REFERENCES "auth_group" ("id"))
CREATE TABLE "accounts_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "name" varchar(100) NOT NULL, "is_active" bool NOT NULL, "is_staff" bool NOT NULL, "date_joined" date NOT NULL, "username" varchar(30) NOT NULL UNIQUE)
CREATE TABLE "accounts_passwordreset" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "confirmed" bool NOT NULL, "user_id" integer NOT NULL REFERENCES "accounts_user" ("id"), "key" varchar(100) NOT NULL)
CREATE INDEX "django_session_de54fa62" ON "django_session" ("expire_date")
CREATE UNIQUE INDEX "django_content_type_app_label_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model")
CREATE INDEX "django_admin_log_e8701ad4" ON "django_admin_log" ("user_id")
CREATE INDEX "django_admin_log_417f1b1c" ON "django_admin_log" ("content_type_id")
CREATE INDEX "courses_course_2dbcba41" ON "courses_course" ("slug")
CREATE UNIQUE INDEX "auth_permission_content_type_id_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename")
CREATE INDEX "auth_permission_417f1b1c" ON "auth_permission" ("content_type_id")
CREATE UNIQUE INDEX "auth_group_permissions_group_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id")
CREATE INDEX "auth_group_permissions_8373b171" ON "auth_group_permissions" ("permission_id")
CREATE INDEX "auth_group_permissions_0e939a4f" ON "auth_group_permissions" ("group_id")
CREATE UNIQUE INDEX "accounts_user_user_permissions_user_id_2ab516c2_uniq" ON "accounts_user_user_permissions" ("user_id", "permission_id")
CREATE INDEX "accounts_user_user_permissions_e8701ad4" ON "accounts_user_user_permissions" ("user_id")
CREATE INDEX "accounts_user_user_permissions_8373b171" ON "accounts_user_user_permissions" ("permission_id")
CREATE UNIQUE INDEX "accounts_user_groups_user_id_59c0b32f_uniq" ON "accounts_user_groups" ("user_id", "group_id")
CREATE INDEX "accounts_user_groups_e8701ad4" ON "accounts_user_groups" ("user_id")
CREATE INDEX "accounts_user_groups_0e939a4f" ON "accounts_user_groups" ("group_id")
CREATE INDEX "accounts_passwordreset_e8701ad4" ON "accounts_passwordreset" ("user_id")
COMMIT
